In [1]:
import numpy
import os
import pandas
import zipfile

In [2]:
ZF = zipfile.ZipFile(
    file='./Input/Mtblmcs_Personal20240917_PGCMetaMetabolomics.zip',
    mode='r')

FH = ZF.open(name='DBDF.bsng.tsv',
             mode='r')
MtblmcsVlsDF = pandas.read_csv(filepath_or_buffer=FH,
                               sep='\t')
FH.close()
del FH

FH = ZF.open(name='DBColumnsDF.bsng.tsv',
             mode='r')
MtblmcsClmnsDF = pandas.read_csv(filepath_or_buffer=FH,
                                 sep='\t')
FH.close()
del FH

FH = ZF.open(name='MetaboliteClasses.bsng.tsv',
             mode='r')
MtblmcsClsssDF = pandas.read_csv(filepath_or_buffer=FH,
                                 sep='\t')
FH.close()
del FH

ZF.close()
del ZF

In [3]:
Path = os.path.join('/home',
                    'rpool',
                    'ownCloud',
                    'Shared',
                    'PRS_Allelica',
                    'documentation',
                    'DataRequestNTR',
                    'DataDownload',
                    'PHE_20240405_4402_LL.sav')
PhenoDF = pandas.read_spss(path=Path)
PhenoDF['FISNumber'] = PhenoDF['FISNumber'].astype(int)
PhenoDF['lifetime_mdd'].dropna()
PhenoDF['MDD_status'] = numpy.nan
F = PhenoDF['lifetime_mdd'].eq('no')
PhenoDF.loc[F,
            'MDD_status'] = 0.0
del F
F = PhenoDF['lifetime_mdd'].eq('yes')
PhenoDF.loc[F,
            'MDD_status'] = 1.0
del F

In [4]:
print(MtblmcsVlsDF.shape)
print(PhenoDF.shape)
MDF = MtblmcsVlsDF.merge(right=PhenoDF[['FISNumber',
                                        'MDD_status']],
                         left_on=['fisnumber'],
                         right_on=['FISNumber'])
print(MDF.shape)
print(MDF.dropna(subset=['MDD_status']).shape)
print(MDF['MDD_status'].value_counts())

(5212, 232)
(43867, 68)
(5212, 234)
(627, 234)
MDD_status
0.0    451
1.0    176
Name: count, dtype: int64

In [5]:
Columns = pandas.Series(MDF.columns)
Columns.index = Columns.values
Columns = Columns.str.replace(pat='^bsng_',
                              repl='',
                              regex=True)
MDF = MDF.rename(columns=Columns.to_dict())
del Columns
MDF

,PID,fisnumber,src_indicator,biobank_indicator,batch_indicator,XXL-VLDL-P,XXL-VLDL-L,XXL-VLDL-PL,XXL-VLDL-C,XXL-VLDL-CE,...,Ace,AcAce,bOHBut,Crea,Alb,Gp,UnSat,Gln,FISNumber,MDD_status
0,514352372616,514352372616,brainshake1_nmr_biobank1,1,0,1.329000e-10,0.02850,0.003121,0.005494,0.003420,...,0.06738,0.03606,0.05437,0.06213,0.07929,1.4350,NaN,NaN,514352372616,NaN
1,514352372487,514352372487,brainshake1_nmr_biobank1,1,0,1.309000e-10,0.02818,0.003320,0.005469,0.003240,...,0.06054,0.03641,0.02598,0.05530,0.07696,1.0880,NaN,NaN,514352372487,NaN
2,514361277651,514361277651,brainshake1_nmr_biobank1,1,0,5.609000e-11,0.01193,0.001461,0.001915,0.001054,...,0.06200,0.03172,0.04472,0.05767,0.08364,1.0370,NaN,NaN,514361277651,NaN
3,514352396617,514352396617,brainshake1_nmr_biobank1,1,0,7.896000e-11,0.01692,0.001884,0.003317,0.002175,...,0.04891,0.02311,0.03327,0.05341,0.08171,1.2480,NaN,NaN,514352396617,NaN
4,514351786793,514351786793,brainshake1_nmr_biobank1,1,0,3.732000e-10,0.08000,0.009436,0.014210,0.007698,...,0.05799,0.03594,0.05332,0.08442,0.08255,1.3230,NaN,NaN,514351786793,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5207,514357547245,514357547245,nightingale2017_nmr_biobank2,2,2,2.213000e-10,0.04697,0.005161,0.007729,0.004523,...,0.10440,0.02935,0.13420,0.06189,0.07158,1.4390,0.8332,NaN,514357547245,NaN
5208,514357547967,514357547967,nightingale2017_nmr_biobank2,2,2,0.000000e+00,0.00000,0.000000,0.000000,0.000000,...,0.08895,0.03871,0.11540,0.06151,0.08735,1.0460,NaN,NaN,514357547967,NaN
5209,514337221955,514337221955,nightingale2017_nmr_biobank2,2,2,1.245000e-10,0.02581,0.002600,0.003012,0.001814,...,0.05925,0.02292,0.08618,0.04050,0.07402,0.9612,NaN,NaN,514337221955,NaN
5210,514337221096,514337221096,nightingale2017_nmr_biobank2,2,2,0.000000e+00,0.00000,0.000000,0.000000,0.000000,...,0.07205,0.02750,0.10330,0.04134,0.07600,1.1360,NaN,NaN,514337221096,NaN
5211,514357827408,514357827408,nightingale2017_nmr_biobank2,2,2,0.000000e+00,0.00000,0.000000,0.000000,0.000000,...,0.07972,0.02694,0.17950,0.07007,0.08703,1.0100,NaN,NaN,514357827408,NaN

In [6]:
print(MDF.shape)
DropColumns = numpy.intersect1d(ar1 = MtblmcsClsssDF.loc[~MtblmcsClsssDF['boInclude'],
                                                   'Name1'],
                                ar2 = MDF.columns).tolist()
MDF = MDF.drop(labels=DropColumns,
               axis=1)
del DropColumns
print(MDF.shape)

(5212, 234)
(5212, 67)

In [9]:
Columns = pandas.Series(MDF.columns)
F = Columns.str.contains(pat='indicator')
F = F | Columns.str.contains(pat='umber')
F = F | Columns.str.contains(pat='PID')
F = F | Columns.str.contains(pat='MDD_status')
F.value_counts()

False    60
True      7
Name: count, dtype: int64

In [8]:
MDF.to_csv(path_or_buf='./Output/MDF.tsv',
           sep='\t',
           index=False)